version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TuPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - inventory_network

  api:
    build:
      context: ./inventory_aplication
      dockerfile: Dockerfile
    container_name: inventory_api
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=InventoryDataBase;User Id=sa;Password=TuPassword123!;TrustServerCertificate=True;"
    depends_on:
      - db
    networks:
      - inventory_network

networks:
  inventory_network:
    driver: bridge
